### ISSUE TITLE
US_06.003 | Organisation folder > Scan Organization Folder Log

### ISSUE THREAD

**Issue by valya-kitty** [RedRoverSchool/JenkinsQA_JS_2024_fall#32]
**Descriptions**
As a Jenkins administrator, I want to be able to view scan logs for the Organization folder to monitor the status and results of automatic discovery and update of projects in the Organization folder, as well as diagnose any problems that arise during the scan process.

**Acceptance criteria**
A User is able to:
**1. Turn on/of Scan Organization Folder Triggers**
- Check in/Check out Periodically if not otherwise run

**2. Set Interval if Periodically if not otherwise run check in**

**Out of scope as discussed with Nalya**

**Comment by NShakiro** [comment]
@valya-kitty please add precondition

**Comment by valya-kitty** [comment]
Out of scope as discussed with Nalya
