### ISSUE TITLE
US_06.004 | Organisation folder > Organization Folder Events

### ISSUE THREAD

**Issue by valya-kitty** [RedRoverSchool/JenkinsQA_JS_2024_fall#33]
**Descriptions**
As a Jenkins administrator, I want to view and manage events related to the Organization Folder, so that I can monitor actions, detect issues, and track changes within the folder’s projects and configurations.

**Acceptance Criteria:**

**_Access to Organization Folder Events:_**
- Jenkins administrator can go to the Organization Folder and view a dedicated "Events" section where I can see a timeline or list of recent events within the folder.
- Events should include project creation, updates, deletion, changes to configuration settings, and other significant actions.

**Comment by valya-kitty** [comment]
**Descriptions**
As a Jenkins administrator, I want to view and manage events related to the Organization Folder, so that I can monitor actions, detect issues, and track changes within the folder’s projects and configurations.

**Acceptance Criteria:**

**_Access to Organization Folder Events:_**
- Jenkins administrator can go to the Organization Folder and view a dedicated "Events" section where I can see a timeline or list of recent events within the folder.
- Events should include project creation, updates, deletion, changes to configuration settings, and other significant actions.

**Comment by NShakiro** [comment]
@valya-kitty please add precondition

**Comment by valya-kitty** [comment]
Out of scope as discussed with Nalya
